language: node_js
node_js:
  - 11.6.0
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: 11.6.0
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      language: generic
notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
before_script:
  - git lfs pull
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release"
    else
      yarn release
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
branches:
  only:
    - master
    - prod
deploy:
  provider: releases
  api_key: "8f5fd6dc02cf011ae061f63f5e6eb20f131a9c44"
  file: "*.snap"
  file_glob: true
  on:
    repo: klouddy/confernece-talk-process-mp3-electron
  skip_cleanup: 'true'
